export {
  RESOURCE_BOUND,
  confirmResourceBound,
  crossover,
  decide,
  isResourceBound,
  type Bottleneck,
  type Crossover,
  type CrossoverInput,
  type Decision,
  type DecisionInput,
  type Exit,
} from './optimization-roi.js';
export {
  SHOPFLOW_INDEXING_CONTENTION,
  checkPhysicalSeparation,
  diagnose,
  validateBackgroundBudget,
  type BackgroundBudget,
  type ContentionObservation,
  type Diagnosis,
  type Placement,
  type SeparationViolation,
} from './contention.js';
export {
  HEADROOM_CEILING,
  HEADROOM_FLOOR,
  MAX_DAYS_SINCE_DRILL,
  MAX_SCALING_MINUTES,
  MODEL_INVALIDATORS,
  assessHeadroom,
  assessModel,
  assessScalingReadiness,
  type HeadroomAssessment,
  type HeadroomZone,
  type ModelVerdict,
  type ReadinessVerdict,
  type Recalibration,
  type ScalingProcedure,
} from './capacity-model.js';
export {
  ITERATIVE_SEQUENCE,
  PERCEPTIBILITY_FLOOR_MS,
  SHOPFLOW_OPTIMIZATIONS,
  judge,
  nextStep,
  opportunityCost,
  type Judgement,
  type Optimization,
  type OpportunityCost,
} from './good-enough.js';
